version: '3'

services:
  gateway:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker --entryPoints.http.address=:80
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: tvsjsdock/teastore-db:v2
    ports:
      - "3306:3306"
    labels:
      - "traefik.enable=false"
  persistence:
    image: tvsjsdock/teastore-persistence:v2
    depends_on:
      - db
    # image: tvsjsdock/teastore-persistence:v2
    expose:
      - "80"
    environment:
      HOST_NAME: "persistence"
      GATEWAY_HOST: "gateway"
      DB_HOST: "db"
      DB_PORT: "3306"
    labels:
      - "traefik.http.routers.persistence.rule=Host(`localhost`) && PathPrefix(`/api/persistence`)"
      - "traefik.port=80"
      - "traefik.protocol=http"
  image:
    image: tvsjsdock/teastore-image:v2
      depends_on:
        - db
    expose:
      - "80"
    environment:
      HOST_NAME: "image"
      GATEWAY_HOST: "gateway"
    labels:
      - "traefik.http.routers.image.rule=Host(`localhost`) && PathPrefix(`/api/image`)"
      - "traefik.port=80"
      - "traefik.protocol=http"
  auth:
    image: tvsjsdock/teastore-auth:v2
    depends_on:
      - db
    expose:
      - "80"
    environment:
      HOST_NAME: "auth"
      GATEWAY_HOST: "gateway"
    labels:
      - "traefik.http.routers.image.rule=Host(`localhost`) && PathPrefix(`/api/auth`)"
      - "traefik.port=80"
      - "traefik.protocol=http"
  recommender:
    image: tvsjsdock/teastore-recommender:v2
    depends_on:
      - db
    expose:
      - "80"
    environment:
      HOST_NAME: "recommender"
      GATEWAY_HOST: "gateway"
    labels:
      - "traefik.http.routers.image.rule=Host(`localhost`) && PathPrefix(`/api/recommender`)"
      - "traefik.port=80"
      - "traefik.protocol=http"
  web:
    image: tvsjsdock/teastore-web:v2
    depends_on:
      - persistence
      - image
      - auth
      - recommender
    expose:
      - "80"
    environment:
      HOST_NAME: "web"
      GATEWAY_HOST: "gateway"
    labels:
      - "traefik.http.routers.web.rule=Host(`localhost`) && PathPrefix(`/api/web`)"
      - "traefik.port=80"
      - "traefik.protocol=http"