version: '3.9'

services:
  gateway:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    # Traefik configuration
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--experimental.http3=true"
      - "--serversTransport.insecureSkipVerify=true"
      - "--entryPoints.http3.address=:4433"
      - "--entrypoints.http3.enablehttp3=true"
    ports:
      # HTTP/3 ports
      - "4433:4433/tcp"
      - "4433:4433/udp"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: tvsjsdock/teastore-db:v2
    ports:
      - "3306:3306"
    labels:
      - "traefik.enable=false"
  persistence:
    image: tvsjsdock/teastore-persistence:v2
    depends_on:
      - db
    expose:
      - "4433/tcp"
      - "4433/udp"
    environment:
      VERSION: "HTTP/3"
      HOST_NAME: "persistence"
      GATEWAY_HOST: "gateway"
      DB_HOST: "db"
      DB_PORT: "3306"
    labels:
      - "traefik.http.routers.persistence.rule=Host(`gateway`) && PathPrefix(`/api/persistence`)"
      - "traefik.http.routers.persistence.entrypoints=http3"
      - "traefik.http.routers.persistence.tls=true"
      - "traefik.http.routers.persistence.service=persistence"
      - "traefik.http.services.persistence.loadbalancer.server.port=4433"
      - "traefik.http.services.persistence.loadbalancer.server.scheme=https"
  auth:
    image: tvsjsdock/teastore-auth:v2
    depends_on:
      - persistence
    expose:
      - "4433/tcp"
      - "4433/udp"
    environment:
      VERSION: "HTTP/3"
      HOST_NAME: "auth"
      GATEWAY_HOST: "gateway"
    labels:
      - "traefik.http.routers.auth.rule=Host(`gateway`) && PathPrefix(`/api/auth`)"
      - "traefik.http.routers.auth.entrypoints=http3"
      - "traefik.http.routers.auth.tls=true"
      - "traefik.http.routers.auth.service=auth"
      - "traefik.http.services.auth.loadbalancer.server.port=4433"
      - "traefik.http.services.auth.loadbalancer.server.scheme=https"
  web:
    image: tvsjsdock/teastore-web:v2
    depends_on:
      - auth
    expose:
      - "4433/tcp"
      - "4433/udp"
    environment:
      VERSION: "HTTP/3"
      HOST_NAME: "web"
      GATEWAY_HOST: "gateway"
    labels:
      - "traefik.http.routers.web.rule=Host(`localhost`) && PathPrefix(`/api/web`)"
      - "traefik.http.routers.web.entrypoints=http3"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.service=web"
      - "traefik.http.services.web.loadbalancer.server.port=4433"
      - "traefik.http.services.web.loadbalancer.server.scheme=https"
  image:
    image: tvsjsdock/teastore-image:v2
    depends_on:
      - persistence
    expose:
      - "4433/tcp"
      - "4433/udp"
    environment:
      VERSION: "HTTP/3"
      HOST_NAME: "image"
      GATEWAY_HOST: "gateway"
    labels:
      - "traefik.http.routers.image.rule=Host(`gateway`) && PathPrefix(`/api/image`)"
      - "traefik.http.routers.image.entrypoints=http3"
      - "traefik.http.routers.image.tls=true"
      - "traefik.http.routers.image.service=image"
      - "traefik.http.services.image.loadbalancer.server.port=4433"
      - "traefik.http.services.image.loadbalancer.server.scheme=https"
  recommender:
    image: tvsjsdock/teastore-recommender:v2
    depends_on:
      - persistence
    expose:
      - "4433/tcp"
      - "4433/udp"
    environment:
      VERSION: "HTTP/3"
      HOST_NAME: "recommender"
      GATEWAY_HOST: "gateway"
    labels:
      - "traefik.http.routers.recommender.rule=Host(`gateway`) && PathPrefix(`/api/recommender`)"
      - "traefik.http.routers.recommender.entrypoints=http3"
      - "traefik.http.routers.recommender.tls=true"
      - "traefik.http.routers.recommender.service=recommender"
      - "traefik.http.services.recommender.loadbalancer.server.port=4433"
      - "traefik.http.services.recommender.loadbalancer.server.scheme=https"