version: '3.9'

services:
  gateway:
    # Traefik v2.5
    image: traefik:v2.5.0-rc5
    # Configuration
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.h3-persistence.address=:4431/udp"
      - "--entryPoints.h3-auth.address=:4432/udp"
      - "--entryPoints.h3-web.address=:4433/udp"
      - "--entryPoints.h3-image.address=:4434/udp"
      - "--entryPoints.h3-recommender.address=:4435/udp"
    ports:
      # The HTTP/3 ports
      - "4431:4431/udp"
      - "4432:4432/udp"
      - "4433:4433/udp"
      - "4434:4434/udp"
      - "4435:4435/udp"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    build: database
    ports:
      - "3306:3306"
    labels:
      - "traefik.enable=false"
  persistence:
    build: services/persistence
    depends_on:
      - db
    expose:
      - "4431/udp"
    environment:
      HTTP_VERSION: "HTTP/3"
      HOST_NAME: "persistence"
      GATEWAY_HOST: "gateway"
      PERSISTENCE_PORT: "4431"
      DB_HOST: "db"
      DB_PORT: "3306"
    labels:
      - "traefik.udp.routers.persistence.entrypoints=h3-persistence"
      - "traefik.udp.routers.persistence.service=persistence"
      - "traefik.udp.services.persistence.loadbalancer.server.port=4431"
  auth:
    build: services/auth
    depends_on:
      - persistence
    expose:
      - "4432/udp"
    environment:
      HTTP_VERSION: "HTTP/3"
      HOST_NAME: "auth"
      GATEWAY_HOST: "gateway"
      PERSISTENCE_PORT: "4431"
      AUTH_PORT: "4432"
    labels:
      - "traefik.udp.routers.auth.entrypoints=h3-auth"
      - "traefik.udp.routers.auth.service=auth"
      - "traefik.udp.services.auth.loadbalancer.server.port=4432"
  web:
    build: services/web
    depends_on:
      - auth
    expose:
      - "4433/udp"
    environment:
      HTTP_VERSION: "HTTP/3"
      HOST_NAME: "web"
      GATEWAY_HOST: "gateway"
      PERSISTENCE_PORT: "4431"
      AUTH_PORT: "4432"
      WEB_PORT: "4433"
      IMAGE_PORT: "4434"
      RECOMMENDER_PORT: "4435"
    labels:
      - "traefik.udp.routers.web.entrypoints=h3-web"
      - "traefik.udp.routers.web.service=web"
      - "traefik.udp.services.web.loadbalancer.server.port=4433"
  image:
    build: services/image
    depends_on:
      - persistence
    expose:
      - "4434/udp"
    environment:
      HTTP_VERSION: "HTTP/3"
      HOST_NAME: "image"
      GATEWAY_HOST: "gateway"
      PERSISTENCE_PORT: "4431"
      IMAGE_PORT: "4434"
    labels:
      - "traefik.udp.routers.image.entrypoints=h3-image"
      - "traefik.udp.routers.image.service=image"
      - "traefik.udp.services.image.loadbalancer.server.port=4434"
  recommender:
    build: services/recommender
    depends_on:
      - persistence
    expose:
      - "4435/udp"
    environment:
      HTTP_VERSION: "HTTP/3"
      HOST_NAME: "recommender"
      GATEWAY_HOST: "gateway"
      PERSISTENCE_PORT: "4431"
      RECOMMENDER_PORT: "4435"
    labels:
      - "traefik.udp.routers.recommender.entrypoints=h3-recommender"
      - "traefik.udp.routers.recommender.service=recommender"
      - "traefik.udp.services.recommender.loadbalancer.server.port=4435"