openapi: "3.0.3"
info:
  title: "TeaStore v2 API"
  description: "Netty TeaStore API"
  version: "2.0.0"
servers:
  - url: "http://localhost:8080"
  - url: "https://localhost:443"
paths:
  /api/web/isready:
    get:
      summary: "This methods checks, if the service is ready."
      responses:
        "200":
          description: "OK"
      tags:
        - Web