name: Run tests on development

on:
  push:
    branches:
      - development
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: development
      -
        uses: sormuras/download-jdk@v1
        with:
          feature: 17
      -
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: jdkfile
          jdkFile: ${{ env.JDK_FILE }}
      -
        run: mvn clean install
