name: Test development

on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - uses: joschi/setup-jdk@v2
        with:
          java-version: '16'
      - run: mvn clean install
