name: Build & deploy on master

on:
  push:
    branches:
      - master
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: master
      -
        uses: joschi/setup-jdk@v2
        with:
          java-version: '16'
      -
        run: mvn clean install
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push database
        uses: docker/build-push-action@v2
        with:
          context: ./database
          file: ./database/Dockerfile
          push: true
          tags: tvsjsdock/teastore-db:v2
      -
        name: Build and push persistence
        uses: docker/build-push-action@v2
        with:
          context: ./services/persistence
          file: ./services/persistence/Dockerfile
          push: true
          tags: tvsjsdock/teastore-persistence:v2
      -
        name: Build and push auth
        uses: docker/build-push-action@v2
        with:
          context: ./services/auth
          file: ./services/auth/Dockerfile
          push: true
          tags: tvsjsdock/teastore-auth:v2
      -
        name: Build and push web
        uses: docker/build-push-action@v2
        with:
          context: ./services/web
          file: ./services/web/Dockerfile
          push: true
          tags: tvsjsdock/teastore-web:v2
      -
        name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./services/image
          file: ./services/image/Dockerfile
          push: true
          tags: tvsjsdock/teastore-image:v2
      -
        name: Build and push recommender
        uses: docker/build-push-action@v2
        with:
          context: ./services/recommender
          file: ./services/recommender/Dockerfile
          push: true
          tags: tvsjsdock/teastore-recommender:v2
