name: Build & deploy on master

on:
  push:
    branches:
      - master
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - uses: joschi/setup-jdk@v2
        with:
          java-version: '16'
      - run: mvn clean install

  push-docker:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_tvsjsdockNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push auth
        uses: docker/build-push-action@v2
        with:
          context: services/auth/Dockerfile
          push: true
          tags: tvsjsdock/teastore-auth:v2
      -
        name: Build and push database
        uses: docker/build-push-action@v2
        with:
          context: database/Dockerfile
          push: true
          tags: tvsjsdock/teastore-db:v2
      -
        name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: services/image/Dockerfile
          push: true
          tags: tvsjsdock/teastore-image:v2
      -
        name: Build and push persistence
        uses: docker/build-push-action@v2
        with:
          context: services/persistence/Dockerfile
          push: true
          tags: tvsjsdock/teastore-persistence:v2
      -
        name: Build and push recommender
        uses: docker/build-push-action@v2
        with:
          context: services/recommender/Dockerfile
          push: true
          tags: tvsjsdock/teastore-recommender:v2
      -
        name: Build and push web
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tvsjsdock/teastore-web:v2
